#########################################
#                                       #
#   Server System Configuration         #
#   Programmed by: Bolt61               #
#                                       #
#########################################

deleted_commands:
  - icanhasbukkit
  - me
  - tell
deleted_permissions:
  - bukkit.command
not_deleted_commands:
  - reload
