#########################################
#                                       #
#   Server System Configuration         #
#   Programmed by: Bolt61               #
#                                       #
#########################################

deleted_commands:
  - icanhasbukkit
  - me
  - tell
deleted_permissions:
  - bukkit.command
not_deleted_commands:
  - reload
mysql:
  host: localhost
  database: minecraft
  user: user
  password: pass
  port: 3306
