name: VanillaServer
authors: [Bolt61]
main: ch.bolt61.vanillaserver.ServerStarter
version: 0.0.1
description: A server plugin
website: nartr.ch
contact: bolt61.minecraft@gmail.com

commands:
  set:
    description: Create a position entry
    usage: /set <name>
    aliases: []
  positions:
    description: Get all positions
    usage: /positions
    aliases: [pos]
  remove:
    description: Remove a position entry
    usage: /remove <name>
    aliases: []
  statistics:
    description: Show your statistics
    usage: /statistics
    aliases: [stats]